### PR TITLE
Fix scenarios where browser cannot be detected properly

### PR DESCRIPTION
**Pull request by nicholaspufal**
This should fix https://github.com/pixelass/onwheel-fix/issues/2

I also used the opportunity to move those Safari checks to a separate module (which removed that `detect-browser` dependency from the main code).

I had to bump the version of `eslint-plugin-promise` in order to be able to run `npm install` within my machine (likely one of the dependencies got updated in the meantime?)

Let me know if you have any questions/comments 👍

### CODE REVIEW

**Comment by divoxx** [comment]
@pixelass is this something that will be merged soon? This is causing issues to us.

**Comment by pixelass** [comment]
@divoxx can you remove the last commit? I will build a release after a sucessful merge.

Best if you `reset --hard` to the last commit and then force push. I can review it today.

**Comment by nicholaspufal** [comment]
@pixelass You mean https://github.com/pixelass/onwheel-fix/pull/3/commits/dbaefecf18731da4e94879ed58847417a7692609? I had to add that because for some user agent strings `detect-browser` blows up - and that causes `onwheel-fix` to also blow up. For instance:

```
Mozilla/5.0 (iPhone; CPU iPhone OS 10_3_1 like Mac OS X) AppleWebKit/602.1.50 (KHTML, like Gecko) GSA/26.0.154727556 Mobile/14E304 Safari/602.1
```

(user-agent string coming from the "Google Search" app running on an iPhone)

**Comment by pixelass** [comment]
@nicholaspufal My bad I didn't see.
just remove the built file and push that.

**Comment by nicholaspufal** [comment]
@pixelass Done 👍 Did a push force to get rid of those build files and merged with latest master.

**Comment by pixelass** [comment]
@nicholaspufal v0.3.4 is available. Thx for the fix
cc @divoxx

**Comment by nicholaspufal** [comment]
@pixelass haha no worries. Thank you :)

**Pull request merged**
